channels:
  - conda-forge                     
  - defaults
dependencies:
#  - python=3.7
  - pip
  - matplotlib
  - pymc3=3.9.3
  - doit
  - pyyaml
  - mkl
  - mkl-service
  - pytest
#  - flake8
#  - sphinx
#  - sphinx_rtd_theme
  - conda-ecosystem-user-package-isolation
  
  



